function fault_scarp
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

%open figure
fig_pos = [10, 10, 1250, 750];
fig = figure('name', 'Fault Scarp Age Estimation with Diffusion',...
        'NumberTitle', 'off',... %get rid of the 'Figure 1:'
        'MenuBar', 'none',... %remove 'File', 'Edit', etc. menu
        'ToolBar', 'none',... %remove icon based lower toolbar
        'Resize', 'on',... %enable resizing
        'Position', fig_pos,... %figure size in pixels
        'DeleteFcn', @DeleteFcn,... %function called upon figure close
        'Tag', 'main_window');

%create tabs/panels in the GUI
tabgroup = uitabgroup('Parent', fig);
control_tab = uitab('Parent', tabgroup, 'Title', 'Program Controls');
IC_tab = uitab('Parent', tabgroup, 'Title', 'Initial Conditions');
results_tab = uitab('Parent', tabgroup, 'Title', 'Results');

%CONSTRUCT CONTROL TAB

%table, text above it, and button for loading data
control_table_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0 0 0.17 1],...
        'Title', 'Input Data',...
        'FontSize', 12);
control_table = uitable('Parent', control_table_panel,...
        'ColumnName', {'X'; 'Y'},...
        'Units', 'normalized',...
        'Position', [0.0522 0.08 0.89 0.9],...
        'Tag', 'control_table');
control_buttongroup_load = uibuttongroup('Parent', control_table_panel,...
        'Units', 'normalized',...
        'Position', [0.0522 0.01 0.89 0.06]);
control_button_load = uicontrol(control_buttongroup_load,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.05 .05 .9 .9],...
        'String', 'LOAD DATA',...
        'FontSize', 14,...
        'Callback', @load_data);

%axes, one with exaggeration and one without
control_ax_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0.18 0.5 0.81 0.5],...
        'Title', 'Model Visualization',...
        'FontSize', 12);
control_ax = axes('Parent', control_ax_panel,...
        'Units', 'normalized',...
        'Position', [0.05 0.1 0.925 0.8],...
        'Tag','control_ax',...
        'Box', 'on',...
        'XGrid', 'on',...
        'YGrid', 'on',...
        'NextPlot', 'add');
        control_ax.YLabel.String = 'Y';
        control_ax.XLabel.String = 'X';
        axis equal
%control panel
control_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0.18 0 0.81 0.49],...
        'Title', 'Numerical Controls',...
        'FontSize', 12);
equation_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.725 0.2 0.25],...
        'Title', 'Governing Equation',...
        'Fontsize', 12);
governing_eq = annotation(equation_panel, 'textbox', [0 0 1 1],...
        'String', '$\frac{\partial y}{\partial t} = \kappa\frac{\partial^2 y}{\partial x^2}$',...
        'Interpreter', 'latex',...
        'Fontsize', 30,...
        'HorizontalAlignment', 'center',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
solution_times_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.22 0.725 0.76 0.25],...
        'Title', 'Solution Times',...
        'Fontsize', 12);
solution_time_1 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_1',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.01 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 1');
solution_time_2 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.176 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_2',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.176 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 2');
solution_time_3 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.342 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_3',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.324 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 3');
solution_time_4 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.508 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_4',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.508 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 4');
solution_time_5 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.674 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_5',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.674 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 5');
total_time = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.84 0.05 0.15 .6],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'total_time',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.84 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'TOTAL TIME');
parameter_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.01 0.49 0.7],...
        'Title', 'Solver Parameters',...
        'Fontsize', 12);
kappa = uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.8 0.45 .2],...
        'Style', 'edit',...
        'Fontsize', 12,...
        'Tag', 'kappa',...
        'Callback', @check_numerical_input);
        annotation(parameter_panel, 'textbox', [0.05 0.8 0.45 0.2],...
        'String', 'Kappa ($\kappa$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
delta_x = uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.6 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'delta_x');
        annotation(parameter_panel, 'textbox', [0.05 0.6 0.45 0.2],...
        'String', 'Spatial Resolution ($\Delta x$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
N_x = uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.4 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'N_x');
        annotation(parameter_panel, 'textbox', [0.05 .4 0.45 0.2],...
        'String', 'Spatial Sample Count ($N_x$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
delta_t = uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.2 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'delta_t');
        annotation(parameter_panel, 'textbox', [0.05 .2 0.45 0.2],...
        'String', 'Temporal Resolution ($\Delta t$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
N_t = uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.0 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'N_t');
        annotation(parameter_panel, 'textbox', [0.05 0.0 0.45 0.2],...
        'String', 'Temporal Sample Count ($N_t$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');


%CONSTRUCT IC TAB
IC_ax = axes('Parent', IC_tab,...
        'Units', 'normalized',...
        'Tag', 'IC_ax',...
        'Box', 'on',...
        'XGrid', 'on',...
        'YGrid', 'on',...
        'PlotBoxAspectRatioMode', 'manual',...
        'DataAspectRatioMode', 'manual',...
        'NextPlot', 'add');
        IC_ax.YLabel.String = 'Y';
        IC_ax.XLabel.String = 'X';
        IC_ax.Position = [0.05 0.05 0.9 0.78];
        axis equal
        text(0.5, 0.5, {'Load Scarp Profile Data',...
                    'Before Setting Initial Conditions'},...
                    'HorizontalAlignment', 'center',...
                    'VerticalAlignment', 'middle',...
                    'Tag', 'IC_ax_text',...
                    'Fontsize', 14);
IC_buttongroup = uibuttongroup('Parent', IC_tab,...
        'Units', 'normalized',...
        'Position', [0.3 0.845 0.4 0.14],...
        'Title', 'Initial Conditon Controls',...
        'Fontsize', 12);
IC_restore_button = uicontrol('Parent', IC_buttongroup,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [0.01 0.4 0.2375 0.6],...
        'String', 'Restore',...
        'FontSize', 12);
IC_add_seg_button = uicontrol('Parent', IC_buttongroup,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [0.2575 0.4 0.2375 0.6],...
        'String', 'Add Segment',...
        'FontSize', 12);
IC_del_seg_button = uicontrol('Parent', IC_buttongroup,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [0.505 0.4 0.2375 0.6],...
        'String', 'Delete Segment',...
        'FontSize', 12);
IC_help_button = uicontrol('Parent', IC_buttongroup,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [0.7525 0.4 0.2375 0.6],...
        'String', 'Help',...
        'FontSize', 12);
IC_exag_checkbox = uicontrol('Parent', IC_buttongroup,...
        'Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [.333 .1 .666 .2],...
        'String', 'Scale Axes Equally',...
        'FontSize', 12,...
        'Value', 1,...
        'Callback', @rescale_IC_axes);

%CONSTRUCT RESULTS TAB

%

end
