function make_control_tab(tabgroup)

%CONSTRUCT CONTROL TAB
control_tab = uitab('Parent', tabgroup, 'Title', 'Program Controls');

%table, text above it, and button for loading data
control_table_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0 0 0.17 1],...
        'Title', 'Input Data',...
        'FontSize', 12);
control_buttongroup_load = uibuttongroup('Parent', control_table_panel,...
        'Units', 'normalized',...
        'Position', [0.0522 0.92 0.89 0.07]);
%control_button_load
uicontrol(control_buttongroup_load,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.05 .05 .9 .9],...
        'String', 'LOAD DATA',...
        'FontSize', 14,...
        'Callback', @load_data);
%control_table
uitable('Parent', control_table_panel,...
        'ColumnName', {'X'; 'Y'},...
        'ColumnEditable', [true true],...
        'Units', 'normalized',...
        'Position', [0.0522 0.09 0.89 0.82],...
        'Tag', 'control_table',...
        'CellEditCallback', @table_edited);
control_buttongroup_save = uibuttongroup('Parent', control_table_panel,...
        'Units', 'normalized',...
        'Position', [0.0522 0.01 0.89 0.07]);
%control_button_save
uicontrol(control_buttongroup_save,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.05 .05 0.9 0.9],...
        'String', 'Save Edited Data',...
        'FontSize', 14,...
        'ForegroundColor', [0.5 0.5 0.5],...
        'Tag', 'control_button_save',...
        'Callback', @save_data);

%axes, one with exaggeration and one without
control_ax_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0.18 0.5 0.81 0.5],...
        'Title', 'Model Visualization',...
        'FontSize', 12);
control_ax = axes('Parent', control_ax_panel,...
        'Units', 'normalized',...
        'Position', [0.05 0.1 0.925 0.75],...
        'Tag','control_ax',...
        'Box', 'on',...
        'XGrid', 'on',...
        'YGrid', 'on',...
        'NextPlot', 'add');
        control_ax.YLabel.String = 'Y';
        control_ax.XLabel.String = 'X';
        axis equal;
%control_ax_exag_checkbox
uicontrol('Parent', control_ax_panel,...
        'Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [0.333 .875 0.666 .1],...
        'String', 'Scale Axes Equally',...
        'FontSize', 12,...
        'Value', 1,...
        'Callback', @rescale_control_axes);

%control panel
control_panel = uipanel('Parent', control_tab,...
        'Units', 'normalized',...
        'Position', [0.18 0 0.81 0.49],...
        'Title', 'Control Panel',...
        'FontSize', 12);
%governing_eq
equation_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.725 0.2 0.25],...
        'Title', 'Governing Equation',...
        'Fontsize', 12);
annotation(equation_panel, 'textbox', [0 0 1 1],...
        'String', '$\frac{\partial y}{\partial t} = \kappa\frac{\partial^2 y}{\partial x^2}$',...
        'Interpreter', 'latex',...
        'Fontsize', 30,...
        'HorizontalAlignment', 'center',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
solution_times_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.22 0.725 0.57 0.25],...
        'Title', 'Solution Times',...
        'Fontsize', 12);
%solution_time_1
uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.075 0.15 0.575],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_1',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.01 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 1',...
        'Fontsize', 11);
%solution_time_2
solution_time_2 = uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.176 0.075 0.15 0.575],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_2',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.176 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 2',...
        'Fontsize', 11);
%solution_time_3
uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.342 0.075 0.15 0.575],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_3',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.342 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 3',...
        'Fontsize', 11);
%solution_time_4
uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.508 0.075 0.15 0.575],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_4',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.508 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 4',...
        'Fontsize', 11);
%solution_time_5
uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.674 0.075 0.15 0.575],...
        'Style', 'edit',...
        'FontSize', 12,...
        'Tag', 'solution_time_5',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.674 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'Solution Time 5',...
        'Fontsize', 11);
%total_time
uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.84 0.075 0.15 .575],...
        'Style', 'edit',...
        'FontSize', 14,...
        'Tag', 'total_time',...
        'Callback', @check_numerical_input);
        uicontrol('Parent', solution_times_panel,...
        'Units', 'normalized',...
        'Position', [0.84 .7 0.15 0.25],...
        'Style', 'text',...
        'String', 'TOTAL TIME',...
        'Fontsize', 11);
run_buttongroup = uibuttongroup('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.8 0.725 0.19 0.225],...
        'Fontsize', 12);
uicontrol('Parent', run_buttongroup,...
        'Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [0.05 0.05 0.9 0.9],...
        'String', 'RUN SOLVER',...
        'FontSize', 14);
parameter_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.01 0.02 0.48 0.7],...
        'Title', 'Solver Parameters',...
        'Fontsize', 12);
%kappa
uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.8 0.45 .2],...
        'Style', 'edit',...
        'Fontsize', 12,...
        'Tag', 'kappa',...
        'Callback', @check_numerical_input);
        annotation(parameter_panel, 'textbox', [0.05 0.8 0.45 0.2],...
        'String', 'Kappa ($\kappa$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
%delta_x
uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.6 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'delta_x');
        annotation(parameter_panel, 'textbox', [0.05 0.6 0.45 0.2],...
        'String', 'Spatial Resolution ($\Delta x$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
%N_x
uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.4 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'N_x');
        annotation(parameter_panel, 'textbox', [0.05 .4 0.45 0.2],...
        'String', 'Spatial Sample Count ($N_x$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
%delta_t
uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.2 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'delta_t');
        annotation(parameter_panel, 'textbox', [0.05 .2 0.45 0.2],...
        'String', 'Temporal Resolution ($\Delta t$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');
%N_t
uicontrol('Parent', parameter_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.0 0.45 0.2],...
        'Style', 'text',...
        'Fontsize', 15,...
        'Tag', 'N_t');
        annotation(parameter_panel, 'textbox', [0.05 0.0 0.45 0.2],...
        'String', 'Temporal Sample Count ($N_t$):',...
        'Interpreter', 'latex',...
        'Fontsize', 15,...
        'HorizontalAlignment', 'right',...
        'VerticalAlignment', 'middle',...
        'EdgeColor', 'none');

%instructions panel
instruction_panel = uipanel('Parent', control_panel,...
        'Units', 'normalized',...
        'Position', [0.5 0.02 0.49 0.7],...
        'Title', 'Brief Instructions',...
        'Fontsize', 12);

end
